### ISSUE TITLE
Code Guides #1 

### ISSUE THREAD

**Issue by JoGosGitHub** [dhbwPMweb/diamond-scope#1]
@tobuto 
- Code Guides erstellen

bis spätestens **14.5.15**

**Comment by mkqavi** [comment]
@JoGosGitHub Code Guidelines sind eigentlich nicht Teil des Git-Repositories, die Aufgabe gehört nur ins "normale" Scrum-System und auf der Dropbox hochgeladen, daher hier erstmal **closed**.
